sm8650-common: fix building CNE app dependency
Symlink points to /vendor/lib64/libvndfwk_detect_jni.qti_vendor.so.

E AndroidRuntime: java.lang.NoClassDefFoundError: com.qualcomm.qti.VndFwkDetect
E AndroidRuntime: 	at com.qualcomm.qti.cne.relay.WlanStaInfoRelay$CountryCodeRetriever.getIsVendorEnhancedFramework(WlanStaInfoRelay.java:727)
E AndroidRuntime: 	at com.qualcomm.qti.cne.relay.WlanStaInfoRelay$CountryCodeRetriever.retrieveCountryCode(WlanStaInfoRelay.java:792)
E AndroidRuntime: 	at com.qualcomm.qti.cne.relay.WlanStaInfoRelay$4.onCommand(WlanStaInfoRelay.java:255)
E AndroidRuntime: 	at com.qualcomm.qti.cne.hwinterface.NativeAidlServerCallback$CommandWrapper.handleMessage(NativeAidlServerCallback.java:215)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:85)
E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libvndfwk_detect_jni.qti_vendor.so" not found
E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1113)
E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1035)
E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1765)
E AndroidRuntime: 	at com.qualcomm.qti.VndFwkDetect.<clinit>(VndFwkDetect.java:40)

Change-Id: I2c40cda326336598071acb00f0e925671f03ea72